version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: homestay_database
    restart: always
    environment:
      POSTGRES_DB: homestay_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: