CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    avatar_url TEXT,
    role VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    otp_code VARCHAR(255),
    otp_expires_at TIMESTAMP,
    email_change_otp VARCHAR(255),
    email_change_otp_expires_at TIMESTAMP,
    pending_email VARCHAR(255),
    reset_otp_code VARCHAR(255),
    reset_otp_expires_at TIMESTAMP,
    membership_tier VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    address VARCHAR(255) NOT NULL,
    price_per_night NUMERIC(38,2) NOT NULL,
    max_guests INTEGER NOT NULL,
    recommended_guests INTEGER,
    extra_guest_fee NUMERIC(38,2),
    type VARCHAR(50) NOT NULL,
    weekend_price NUMERIC(38,2),
    holiday_price NUMERIC(38,2),
    room_size INTEGER,
    bed_configuration VARCHAR(255),
    view_description VARCHAR(255),
    bathroom_description VARCHAR(255),
    floor VARCHAR(255),
    check_in_time VARCHAR(255),
    check_out_time VARCHAR(255),
    house_rules TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS discount_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    percent INTEGER NOT NULL,
    description VARCHAR(255),
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    guest_count INTEGER NOT NULL,
    total_price NUMERIC(38,2) NOT NULL,
    nights INTEGER,
    base_price NUMERIC(38,2),
    holiday_price NUMERIC(38,2),
    extra_guest_fee NUMERIC(38,2),
    membership_discount_percent INTEGER,
    membership_discount_amount NUMERIC(38,2),
    discount_code VARCHAR(255),
    discount_code_percent INTEGER,
    discount_code_amount NUMERIC(38,2),
    payment_method VARCHAR(50),
    payment_status VARCHAR(50),
    payment_hold_expires_at TIMESTAMP,
    rejection_reason VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    note VARCHAR(255),
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    booking_code VARCHAR(255) UNIQUE,
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_booking_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMP,
    CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES bookings(id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_review_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS room_images (
    room_id BIGINT NOT NULL,
    image_url VARCHAR(255),
    CONSTRAINT fk_room_images_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS room_amenities (
    room_id BIGINT NOT NULL,
    amenity VARCHAR(255),
    CONSTRAINT fk_room_amenities_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_booking_room_dates_status
    ON bookings (room_id, check_in_date, check_out_date, status);
CREATE INDEX IF NOT EXISTS idx_booking_hold_expiry
    ON bookings (status, payment_hold_expires_at);
CREATE INDEX IF NOT EXISTS idx_booking_user_created
    ON bookings (user_id, created_at);
