"use client";
import { useEffect, useState } from "react";
import ProtectedRoute from "@/components/ProtectedRoute";
import { accountService, AccountProfile } from "@/lib/services/accountService";
import { getErrorMessage } from "@/lib/getErrorMessage";

function AccountContent() {
 const [profile,setProfile]=useState<AccountProfile|null>(null); const [fullName,setFullName]=useState(""); const [phone,setPhone]=useState(""); const [newEmail,setNewEmail]=useState(""); const [otp,setOtp]=useState(""); const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [emailSent,setEmailSent]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{ void accountService.getMe().then(d=>{setProfile(d);setFullName(d.fullName);setPhone(d.phone??"");setNewEmail(d.email)}).catch(e=>setError(getErrorMessage(e,"Không thể tải thông tin tài khoản"))).finally(()=>setLoading(false));},[]);
 const notice=(m="",e="")=>{setMessage(m);setError(e)};
 const saveProfile=async(e:React.FormEvent)=>{e.preventDefault();notice();setBusy("profile");try{const d=await accountService.updateProfile({fullName:fullName.trim(),phone:phone.trim()});setProfile(d);setMessage("Thông tin tài khoản đã được cập nhật.");}catch(e){setError(getErrorMessage(e,"Không thể cập nhật thông tin"))}finally{setBusy("")}};
 const changePassword=async(e:React.FormEvent)=>{e.preventDefault();notice();if(newPassword!==confirm)return setError("Mật khẩu xác nhận không khớp.");setBusy("password");try{await accountService.changePassword({currentPassword,newPassword});setCurrentPassword("");setNewPassword("");setConfirm("");setMessage("Đổi mật khẩu thành công.")}catch(e){setError(getErrorMessage(e,"Không thể đổi mật khẩu"))}finally{setBusy("")}};
 const requestEmail=async()=>{notice();if(!newEmail||newEmail===profile?.email)return setError("Vui lòng nhập email mới khác email hiện tại.");setBusy("email");try{await accountService.requestEmailChange({newEmail:newEmail.trim()});setEmailSent(true);setMessage("Mã OTP đã được gửi tới email mới.")}catch(e){setError(getErrorMessage(e,"Không thể gửi mã OTP"))}finally{setBusy("")}};
 const verifyEmail=async(e:React.FormEvent)=>{e.preventDefault();notice();setBusy("verify");try{const d=await accountService.verifyEmailChange({newEmail:newEmail.trim(),otp});setProfile(d);setEmailSent(false);setOtp("");setMessage("Email đã được cập nhật.")}catch(e){setError(getErrorMessage(e,"Mã OTP không đúng hoặc đã hết hạn"))}finally{setBusy("")}};
 if(loading)return <main className="mx-auto max-w-4xl px-4 py-10"><p className="text-sm text-neutral-500">Đang tải thông tin tài khoản...</p></main>;
 return <main className="mx-auto max-w-4xl px-4 py-10"><p className="font-display text-sm italic text-accent">Không gian riêng của bạn</p><h1 className="mt-1 font-display text-3xl text-ink">Tài khoản của tôi</h1><p className="mt-2 text-sm text-neutral-500">Quản lý thông tin và bảo mật tài khoản ForestView.</p>
 {(error||message)&&<div className={`mt-6 rounded-xl border px-4 py-3 text-sm ${error?"border-red-200 bg-red-50 text-red-700":"border-primary/20 bg-primary/5 text-primary"}`}>{error||message}</div>}
 <div className="mt-8 grid gap-6 md:grid-cols-2">
 <section className="rounded-2xl border border-line bg-surface p-6"><h2 className="font-display text-xl text-ink">Thông tin cá nhân</h2><form onSubmit={saveProfile} className="mt-5 space-y-4"><div><label className="text-sm text-neutral-600">Họ và tên</label><input required value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/></div><div><label className="text-sm text-neutral-600">Email hiện tại</label><input disabled value={profile?.email??""} className="mt-1 w-full rounded-lg border border-line bg-base px-3 py-2.5 text-sm text-neutral-500"/></div><div><label className="text-sm text-neutral-600">Số điện thoại</label><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} className="mt-1 w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/></div><button disabled={busy==="profile"} className="w-full rounded-full bg-primary py-3 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-50">{busy==="profile"?"Đang lưu...":"Lưu thông tin"}</button></form></section>
 <section className="rounded-2xl border border-line bg-surface p-6"><h2 className="font-display text-xl text-ink">Đổi mật khẩu</h2><form onSubmit={changePassword} className="mt-5 space-y-4"><input type="password" required placeholder="Mật khẩu hiện tại" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} className="w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/><input type="password" required minLength={6} placeholder="Mật khẩu mới" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/><input type="password" required minLength={6} placeholder="Xác nhận mật khẩu mới" value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/><button disabled={busy==="password"} className="w-full rounded-full border border-primary py-3 text-sm font-semibold text-primary hover:bg-primary hover:text-white disabled:opacity-50">{busy==="password"?"Đang cập nhật...":"Đổi mật khẩu"}</button></form></section>
 <section className="rounded-2xl border border-line bg-surface p-6 md:col-span-2"><h2 className="font-display text-xl text-ink">Thay đổi email</h2><p className="mt-1 text-sm text-neutral-500">Mã OTP sẽ được gửi tới email mới.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input type="email" value={newEmail} onChange={e=>{setNewEmail(e.target.value);setEmailSent(false)}} className="flex-1 rounded-lg border border-line bg-surface px-3 py-2.5 text-sm text-ink focus:border-primary focus:outline-none"/><button type="button" onClick={requestEmail} disabled={busy==="email"} className="rounded-full bg-primary px-6 py-2.5 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-50">{busy==="email"?"Đang gửi...":"Gửi mã OTP"}</button></div>{emailSent&&<form onSubmit={verifyEmail} className="mt-4 flex flex-col gap-3 sm:flex-row"><input required maxLength={6} inputMode="numeric" pattern="[0-9]{6}" placeholder="Mã OTP 6 số" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,""))} className="flex-1 rounded-lg border border-line bg-surface px-3 py-2.5 text-center text-lg tracking-[0.4em] text-ink focus:border-primary focus:outline-none"/><button disabled={busy==="verify"||otp.length!==6} className="rounded-full border border-primary px-6 py-2.5 text-sm font-semibold text-primary hover:bg-primary hover:text-white disabled:opacity-50">{busy==="verify"?"Đang xác nhận...":"Xác nhận email"}</button></form>}</section>
 </div></main>;
}
export default function AccountPage(){return <ProtectedRoute allowedRoles={["USER","ADMIN"]}><AccountContent/></ProtectedRoute>}
