"use client";
import { useEffect, useState } from "react";
import ProtectedRoute from "@/components/ProtectedRoute";
import { accountService, AccountUser } from "@/lib/services/accountService";
import { useAuthStore } from "@/hooks/useAuthStore";
import { getErrorMessage } from "@/lib/getErrorMessage";
import { getAccessToken, getRefreshToken } from "@/lib/auth";

const Input = (p: React.InputHTMLAttributes<HTMLInputElement>) => <input {...p} className={`mt-1 w-full rounded-xl border border-line bg-base px-4 py-3 text-sm focus:border-primary focus:outline-none ${p.className ?? ""}`} />;
function AccountContent(){
 const {user,login}=useAuthStore(); const [profile,setProfile]=useState<AccountUser|null>(null); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [newEmail,setNewEmail]=useState(""); const [emailOtp,setEmailOtp]=useState(""); const [emailStep,setEmailStep]=useState<"idle"|"otp">("idle"); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{void accountService.me().then(d=>{setProfile(d);setName(d.fullName);setPhone(d.phone??"")}).catch(e=>setError(getErrorMessage(e))).finally(()=>setLoading(false))},[]);
 const notice=(e="",m="")=>{setError(e);setMessage(m)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();notice();setBusy(true);try{const d=await accountService.updateProfile({fullName:name.trim(),phone:phone.trim()||undefined});setProfile(d); if(user){login(getAccessToken() ?? "",getRefreshToken() ?? "",{...user,fullName:d.fullName,email:d.email,role:d.role})}notice("","Thông tin cá nhân đã được cập nhật.")}catch(e){notice(getErrorMessage(e,"Không thể cập nhật thông tin."))}finally{setBusy(false)}};
 const changePass=async(e:React.FormEvent)=>{e.preventDefault();notice();if(newPassword!==confirmPassword)return notice("Mật khẩu xác nhận không khớp.");setBusy(true);try{await accountService.changePassword({currentPassword,newPassword});setCurrentPassword("");setNewPassword("");setConfirmPassword("");notice("","Đổi mật khẩu thành công.")}catch(e){notice(getErrorMessage(e,"Không thể đổi mật khẩu."))}finally{setBusy(false)}};
 const requestEmail=async(e:React.FormEvent)=>{e.preventDefault();notice();setBusy(true);try{await accountService.requestEmailChange({newEmail:newEmail.trim()});setEmailStep("otp");notice("","Mã OTP đã được gửi tới email mới.")}catch(e){notice(getErrorMessage(e,"Không thể gửi OTP tới email mới."))}finally{setBusy(false)}};
 const verifyEmail=async(e:React.FormEvent)=>{e.preventDefault();notice();setBusy(true);try{const r=await accountService.verifyEmailChange({newEmail:newEmail.trim(),otp:emailOtp});login(r.accessToken,r.refreshToken,{fullName:r.fullName,email:r.email,role:r.role});setProfile(p=>p?{...p,email:r.email}:p);setEmailStep("idle");setEmailOtp("");notice("","Email đã được thay đổi thành công.")}catch(e){notice(getErrorMessage(e,"Mã OTP không đúng hoặc đã hết hạn."))}finally{setBusy(false)}};
 if(loading)return <main className="mx-auto max-w-4xl px-5 py-16 text-sm text-neutral-500">Đang tải tài khoản...</main>;
 return <main className="mx-auto max-w-4xl px-5 py-10 md:py-14"><div className="mb-8"><p className="font-display text-sm italic text-accent">Không gian riêng của bạn</p><h1 className="mt-1 font-display text-4xl text-ink">Tài khoản của tôi</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-500">Quản lý thông tin cá nhân, bảo mật tài khoản và email của bạn.</p></div>
 {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{message&&<div className="mb-5 rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary">{message}</div>}
 <div className="grid gap-6 lg:grid-cols-2">
 <section className="rounded-3xl border border-line bg-surface p-6 shadow-sm lg:col-span-2"><div className="mb-6 flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-primary text-lg font-semibold text-white">{(profile?.fullName||"U").charAt(0).toUpperCase()}</div><div><h2 className="text-lg font-semibold">Thông tin cá nhân</h2><p className="text-sm text-neutral-500">Thông tin dùng cho đặt phòng và liên hệ.</p></div></div><form onSubmit={save} className="grid gap-5 md:grid-cols-3"><div><label className="text-sm text-neutral-600">Họ và tên</label><Input required value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="text-sm text-neutral-600">Email</label><Input disabled value={profile?.email??""}/></div><div><label className="text-sm text-neutral-600">Số điện thoại</label><Input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0901 234 567"/></div><button disabled={busy} className="w-fit rounded-full bg-primary px-6 py-3 text-sm font-semibold text-white hover:bg-primary-dark disabled:opacity-50">{busy?"Đang lưu...":"Lưu thay đổi"}</button></form></section>
 <section className="rounded-3xl border border-line bg-surface p-6 shadow-sm"><h2 className="text-lg font-semibold">Đổi mật khẩu</h2><p className="mt-1 text-sm text-neutral-500">Cập nhật mật khẩu để bảo vệ tài khoản.</p><form onSubmit={changePass} className="mt-5 space-y-4"><Input type="password" required minLength={6} placeholder="Mật khẩu hiện tại" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/><Input type="password" required minLength={6} placeholder="Mật khẩu mới" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/><Input type="password" required minLength={6} placeholder="Xác nhận mật khẩu mới" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/><button disabled={busy} className="rounded-full border border-primary px-6 py-3 text-sm font-semibold text-primary hover:bg-primary hover:text-white disabled:opacity-50">{busy?"Đang cập nhật...":"Đổi mật khẩu"}</button></form></section>
 <section className="rounded-3xl border border-line bg-surface p-6 shadow-sm"><h2 className="text-lg font-semibold">Thay đổi email</h2><p className="mt-1 text-sm text-neutral-500">Email mới cần xác thực bằng OTP.</p>{emailStep==="idle"?<form onSubmit={requestEmail} className="mt-5 space-y-4"><Input type="email" required placeholder="Email mới" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><button disabled={busy} className="rounded-full border border-primary px-6 py-3 text-sm font-semibold text-primary hover:bg-primary hover:text-white disabled:opacity-50">{busy?"Đang gửi OTP...":"Gửi mã xác nhận"}</button></form>:<form onSubmit={verifyEmail} className="mt-5 space-y-4"><p className="rounded-xl bg-base px-4 py-3 text-sm">Mã OTP đã gửi tới <b>{newEmail}</b>.</p><Input inputMode="numeric" maxLength={6} required placeholder="000000" value={emailOtp} onChange={e=>setEmailOtp(e.target.value.replace(/\D/g,""))} className="text-center text-2xl tracking-[0.45em]"/><div className="flex gap-3"><button disabled={busy||emailOtp.length!==6} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">Xác nhận email</button><button type="button" onClick={()=>setEmailStep("idle")} className="rounded-full border border-line px-5 py-3 text-sm">Quay lại</button></div></form>}</section>
 </div></main>;
}
export default function AccountPage(){return <ProtectedRoute allowedRoles={["USER","ADMIN"]}><AccountContent/></ProtectedRoute>}
